#!/usr/bin/env python3
"""Build static product pages from data/products/*.json.

    python3 scripts/process-images.py        # first, whenever images change
    python3 scripts/build-products.py        # validate, render, write pages, update sitemap + category lists
    python3 scripts/build-products.py --check  # validate + render in memory only; writes nothing

Cloudflare Pages has no build step for this site: run this locally and commit
the generated HTML. Status decides where a record renders:

    draft      nowhere
    preview    preview/<slug>/index.html      noindex, not in the sitemap
    published  <category>/<slug>/index.html   in sitemap.xml and the category page's product list

Requires jinja2. Any validation problem fails the whole build with exit code 1.
"""
import html
import json
import re
import sys
from decimal import ROUND_HALF_UP, Decimal

from jinja2 import Environment, FileSystemLoader, StrictUndefined
from markupsafe import Markup

from productlib import (CATEGORIES, IMAGES_DIR, PRIVATE_DIR, PRIVATE_SCHEMA_PATH, ROOT, SCHEMA_PATH, SITE, BuildError, gbp,
                        load_records, read_json, subtotal, unit_price, validate_schema, web_name)

GENERATED_MARK = '<!-- Generated by scripts/build-products.py'
BLOCK = re.compile(r'(<!-- products:start -->).*?(<!-- products:end -->)', re.S)
# Internal-only material that must never reach a shipped page.
LEAKS = [r'\bfloor\b', r'review_date', r'pricing_source', r'min_qty', r'"internal"', r'"source"', r'"notes"',
         r'ESTIMATE', r'NO SUPPLIER QUOTE', r'Brand Your', r'ACS-\d{4}']


# ---------- validation ----------

def check_record(record, name):
    """Cross-field rules the schema cannot express. Returns a list of problems."""
    errors = []
    err = lambda message: errors.append(f'{name}: {message}')
    options = {o['key']: {v['value'] for v in o['values']} for o in record['options']}
    if len(options) != len(record['options']):
        err('duplicate option key')
    for option in record['options']:
        if sum(1 for v in option['values'] if v.get('default')) != 1:
            err(f'option "{option["key"]}" needs exactly one default value')
    if record['category'] not in CATEGORIES:
        err(f'unknown category "{record["category"]}"')

    pricing = {}
    for entry in record['pricing']:
        if entry['ref'] in pricing:
            err(f'duplicate pricing ref "{entry["ref"]}"')
        pricing[entry['ref']] = entry
        qtys = [t['qty'] for t in entry['tiers']]
        if any(b <= a for a, b in zip(qtys, qtys[1:])):
            err(f'pricing "{entry["ref"]}": tier quantities must be strictly increasing, got {qtys}')
        if qtys and 'min_qty' in entry and qtys[0] < entry['min_qty']:
            err(f'pricing "{entry["ref"]}": first tier {qtys[0]} is below min_qty {entry["min_qty"]}')
        for tier in entry['tiers']:
            if not (tier['unit'] is None or isinstance(tier['unit'], str)):
                err(f'pricing "{entry["ref"]}": unit must be a decimal string or null, not {tier["unit"]!r}')

    seen = set()
    for variant in record['variants']:
        sku, selection = variant['sku'], variant['selection']
        if set(selection) != set(options):
            err(f'variant {sku}: selection must set exactly the declared options {sorted(options)}')
        for key, value in selection.items():
            if key in options and value not in options[key]:
                err(f'variant {sku}: "{value}" is not a declared value of option "{key}"')
        frozen = tuple(sorted(selection.items()))
        if frozen in seen:
            err(f'variant {sku}: duplicate selection {selection}')
        seen.add(frozen)
        mode = variant.get('enquiry', record['enquiry'])['mode']
        ref = variant.get('pricing_ref')
        if ref is not None and ref not in pricing:
            err(f'variant {sku}: pricing_ref "{ref}" does not exist')
        if variant['available'] and mode == 'priced' and ref is None:
            err(f'variant {sku}: available + priced needs a pricing_ref')
        if not variant['available'] and mode == 'priced':
            err(f'variant {sku}: unavailable variants must be enquiry.mode "quote_only" so they are never priced')

    defaults = default_selection(record)
    if not any(v['selection'] == defaults for v in record['variants']):
        err(f'default selection {defaults} is not a declared variant')

    for block, label in [(record['specs'], 'spec'), (record['images'], 'image')]:
        for item in block:
            for key, value in item.get('applies_to', item.get('match', {})).items():
                if key not in options or value not in options[key]:
                    err(f'{label} "{item.get("label")}": {key}={value} is not a declared option value')

    manifest = load_manifest(record['slug'])
    present = 0
    for image in record['images']:
        stem = web_name(image['file'])
        files = [IMAGES_DIR / record['slug'] / f'{stem}{suffix}' for suffix in ('.webp', '.jpg', '-thumb.webp')]
        if stem in manifest and all(f.exists() for f in files):
            present += 1
        elif not image.get('optional'):
            err(f'image missing from assets/images/products/{record["slug"]}/ — {stem} (run scripts/process-images.py)')
    if not present:
        err('no usable images')

    if record['status'] == 'published':
        sellable = any(
            v['available'] and (v.get('enquiry', record['enquiry'])['mode'] == 'quote_only'
                                or any(t['unit'] for t in pricing.get(v.get('pricing_ref'), {}).get('tiers', [])))
            for v in record['variants'])
        if not sellable:
            err('status "published" needs at least one available variant with a price, or enquiry.mode "quote_only"')
        if record['seo']['canonical'] != f'/{record["category"]}/{record["slug"]}/':
            err(f'seo.canonical must be /{record["category"]}/{record["slug"]}/ to match where the page is written')
    return errors


def validate(records):
    """Schema-check the public files and their private companions as written, then cross-check the merged records."""
    schema, private_schema = read_json(SCHEMA_PATH), read_json(PRIVATE_SCHEMA_PATH)
    errors, skus, slugs = [], {}, {}
    for path, record in records:
        problems = [f'{path.name}: {e}' for e in validate_schema(read_json(path), schema)]
        private_path = PRIVATE_DIR / path.name
        if private_path.exists():
            private = read_json(private_path)
            problems += [f'private/{path.name}: {e}' for e in validate_schema(private, private_schema)]
            refs = {p['ref'] for p in record.get('pricing', []) if isinstance(p, dict) and 'ref' in p}
            if not problems and set(private['pricing']) != refs:
                problems.append(f'private/{path.name}: pricing keys {sorted(private["pricing"])} do not match the record\'s refs {sorted(refs)}')
        else:
            print(f'  note     data/private/{path.name} not found — building without internal pricing metadata')
        errors += problems
        if problems:
            continue  # cross-field checks assume schema-valid files
        errors += check_record(record, path.name)
        for variant in record['variants']:
            if variant['sku'] in skus:
                errors.append(f'{path.name}: SKU {variant["sku"]} already used in {skus[variant["sku"]]}')
            skus[variant['sku']] = path.name
        for key in ('id', 'slug'):
            if (key, record[key]) in slugs:
                errors.append(f'{path.name}: {key} "{record[key]}" already used in {slugs[(key, record[key])]}')
            slugs[(key, record[key])] = path.name
    if errors:
        raise BuildError('\n'.join(errors))


# ---------- rendering ----------

def load_manifest(slug):
    path = IMAGES_DIR / slug / 'manifest.json'
    return json.loads(path.read_text()) if path.exists() else {}


def default_selection(record):
    return {o['key']: next((v['value'] for v in o['values'] if v.get('default')), o['values'][0]['value'])
            for o in record['options']}


def matches(partial, selection):
    return all(selection.get(k) == v for k, v in partial.items())


def markdown(text):
    """Paragraphs, **bold**, *italic* and [links](/path/ or https://…) — nothing else."""
    out = []
    for block in re.split(r'\n\s*\n', text.strip()):
        block = html.escape(block, quote=False)
        block = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', block)
        block = re.sub(r'\*(.+?)\*', r'<em>\1</em>', block)
        block = re.sub(r'\[([^\]]+)\]\(((?:/|https://)[^)\s"]*)\)', r'<a href="\2">\1</a>', block)
        out.append(f'<p>{block}</p>')
    return Markup(''.join(out))


def script_json(value):
    """JSON safe to inline inside a <script> element."""
    return Markup(json.dumps(value, ensure_ascii=False, separators=(',', ':')).replace('<', '\\u003c'))


def web_images(record):
    """Record images that exist on disk, with web paths and pixel sizes. Order matches the record."""
    manifest, base, images = load_manifest(record['slug']), f'/assets/images/products/{record["slug"]}', []
    for image in record['images']:
        stem = web_name(image['file'])
        if stem not in manifest:
            continue  # optional shot not delivered yet (required ones already failed validation)
        size = manifest[stem]
        images.append({'src': f'{base}/{stem}.webp', 'jpg': f'{base}/{stem}.jpg', 'thumb': f'{base}/{stem}-thumb.webp',
                       'w': size['width'], 'h': size['height'], 'tw': size['thumb_width'], 'th': size['thumb_height'],
                       'alt': image['alt'], 'role': image['role'],
                       'order': image['order'], 'match': image['match']})
    return images


def gallery_for(images, selection):
    """Same ordering as renderGallery() in product-page.js."""
    matched = sorted((i for i in images if i['role'] != 'inspiration' and matches(i['match'], selection)),
                     key=lambda i: (i['role'] != 'hero', -len(i['match']), i['order']))
    inspiration = sorted((i for i in images if i['role'] == 'inspiration' and matches(i['match'], selection)),
                         key=lambda i: i['order'])
    seen, gallery = set(), []
    for image in matched + inspiration:
        if image['src'] not in seen:
            seen.add(image['src'])
            gallery.append(image)
    return gallery


def variant_mode(record, variant):
    return variant.get('enquiry', record['enquiry'])['mode']


def priced_tiers(record, variant, selection):
    """[(qty, unit Decimal|None)] for a variant, or [] when it is quote-only/unavailable."""
    if not (variant and variant['available'] and variant_mode(record, variant) == 'priced' and variant.get('pricing_ref')):
        return []
    entry = next(p for p in record['pricing'] if p['ref'] == variant['pricing_ref'])
    mults = [v['mult'] for o in record['options'] for v in o['values'] if v['value'] == selection[o['key']] and v.get('mult')]
    return [(t['qty'], unit_price(t['unit'], mults)) for t in entry['tiers']]


def price_table(record, chosen):
    """Static base-price table (default option values) for the no-JavaScript fallback."""
    qtys = sorted({t['qty'] for p in record['pricing'] for t in p['tiers']})
    rows, varying = [], set()
    for entry in record['pricing']:
        users = [v for v in record['variants'] if v.get('pricing_ref') == entry['ref'] and v['available']]
        if not users:
            continue
        fixed = {k: v for k, v in users[0]['selection'].items() if all(u['selection'][k] == v for u in users)}
        keys = [o['key'] for o in record['options'] if o['key'] in fixed
                and len({v['selection'][o['key']] for v in record['variants']}) > 1]
        varying.update(keys)
        label = ' · '.join(next(v['label'] for o in record['options'] if o['key'] == k for v in o['values'] if v['value'] == fixed[k]) for k in keys)
        units = {t['qty']: t['unit'] for t in entry['tiers']}
        rows.append({'label': label or entry['ref'],
                     'cells': ['—' if q not in units else 'POA' if units[q] is None else gbp(unit_price(units[q], []), 3) for q in qtys]})
    heading = ' / '.join(o['label'] for o in record['options'] if o['key'] in varying) or 'Option'
    base = ', '.join(f'{v["label"]} {o["label"].lower()}' for o, v in zip(record['options'], chosen) if o['key'] not in varying)
    return {'row_heading': heading, 'base': base, 'qtys': [f'{q:,}' for q in qtys], 'rows': rows}


def page_data(record, images, defaults):
    """The JSON the page ships. Built field by field — a whitelist — so nothing internal can ride along."""
    return {
        'id': record['id'], 'title': record['title'], 'unit': record['copy']['unit'],
        'options': [{'key': o['key'], 'label': o['label'],
                     'values': [{k: v[k] for k in ('value', 'label', 'mult', 'note') if k in v} for v in o['values']]}
                    for o in record['options']],
        'defaults': defaults,
        'variants': [{'sku': v['sku'], 'selection': v['selection'], 'available': v['available'],
                      'mode': variant_mode(record, v),
                      **({'pricing_ref': v['pricing_ref']} if v.get('pricing_ref') else {}),
                      **({'lead_time': v['lead_time']['text']} if v.get('lead_time') else {})}
                     for v in record['variants']],
        'pricing': {p['ref']: [[t['qty'], t['unit']] for t in p['tiers']] for p in record['pricing']},
        'charges': [{'label': c['label'], 'amount': c['amount']} for c in record['charges']],
        'lead_time': record['lead_time']['text'],
        'images': images,
    }


def render(env, record):
    defaults = default_selection(record)
    images = web_images(record)
    gallery = gallery_for(images, defaults)
    variant = next(v for v in record['variants'] if v['selection'] == defaults)
    tiers = priced_tiers(record, variant, defaults)
    unit_word = record['copy']['unit']
    charges = sum((Decimal(c['amount']) for c in record['charges']), Decimal(0))

    priced = [(q, u) for q, u in tiers if u is not None]
    first = priced[0][1] if priced else None
    tier_cards = []
    for qty, unit in tiers:
        if unit is None:
            tier_cards.append({'qty': qty, 'qty_text': f'{qty:,}', 'unit_text': 'POA', 'subtotal_text': 'Price on request', 'save_text': ''})
            continue
        saving = int(((first - unit) * 100 / first).quantize(Decimal(1), rounding=ROUND_HALF_UP)) if first and first > unit else 0
        tier_cards.append({'qty': qty, 'qty_text': f'{qty:,}', 'unit_text': gbp(unit, 3),
                           'subtotal_text': f'{gbp(subtotal(qty, unit), 2)} total',
                           'save_text': f'Save {saving}%' if saving > 0 else 'Starting quantity'})
    order_rows, total_text = [], 'Price on request'
    if tiers and tiers[0][1] is not None:
        qty, unit = tiers[0]
        order_rows = [{'label': f'Unit price · {qty:,} {unit_word["many"]}', 'value': f'{gbp(unit, 3)} / {unit_word["one"]}'},
                      {'label': 'Subtotal', 'value': gbp(subtotal(qty, unit), 2)}]
        order_rows += [{'label': c['label'], 'value': f'£{c["amount"]}'} for c in record['charges']]
        total_text = gbp(subtotal(qty, unit) + charges, 2)

    chosen = [next(v for v in o['values'] if v['value'] == defaults[o['key']]) for o in record['options']]
    notes = [v['note'] for v in chosen if v.get('note')]
    if not tiers:
        notes.append('Tell us the quantity you need and we’ll price this configuration for you.')
    published = record['status'] == 'published'
    canonical = SITE + record['seo']['canonical']
    crumbs = [('Home', f'{SITE}/'), (CATEGORIES[record['category']], f'{SITE}/{record["category"]}/'), (record['title'], canonical)]
    breadcrumb_ld = {'@context': 'https://schema.org', '@type': 'BreadcrumbList', 'itemListElement': [
        {'@type': 'ListItem', 'position': i + 1, 'name': name, 'item': url} for i, (name, url) in enumerate(crumbs)]}
    faq_ld = {'@context': 'https://schema.org', '@type': 'FAQPage', 'mainEntity': [
        {'@type': 'Question', 'name': f['q'], 'acceptedAnswer': {'@type': 'Answer', 'text': f['a']}} for f in record['faqs']]}

    return env.get_template('product.html').render(
        p=record, copy=record['copy'], site=SITE, published=published, canonical=canonical, category_label=CATEGORIES[record['category']],
        hero=gallery[0], gallery=gallery, defaults=defaults,
        default_labels={o['key']: v['label'] for o, v in zip(record['options'], chosen)},
        default_note=' '.join(notes), tiers=tier_cards, order_rows=order_rows, total_text=total_text,
        from_price=gbp(min(u for _, u in priced), 3) if priced else 'Price on request',
        default_lead_time=(variant.get('lead_time') or record['lead_time'])['text'] if variant['available']
        else 'Availability and lead time confirmed with your quote',
        price_table=price_table(record, chosen),
        description_html=markdown(record['description']),
        specs=[{'label': s['label'], 'value': s['value'],
                'applies': json.dumps(s['applies_to'], separators=(',', ':')) if s.get('applies_to') else '',
                'hidden': not matches(s.get('applies_to', {}), defaults)} for s in record['specs']],
        breadcrumb_ld=script_json(breadcrumb_ld), faq_ld=script_json(faq_ld) if record['faqs'] else '',
        product_json=script_json(page_data(record, images, defaults)))


def check_leaks(page, name):
    found = [pattern for pattern in LEAKS if re.search(pattern, page)]
    if found:
        raise BuildError(f'{name}: internal data leaked into rendered HTML — matched {found}')


# ---------- outputs ----------

def target_for(record):
    if record['status'] == 'preview':
        return ROOT / 'preview' / record['slug'] / 'index.html'
    if record['status'] == 'published':
        return ROOT / record['category'] / record['slug'] / 'index.html'
    return None


def remove_stale(record, keep):
    """Delete this record's generated page from wherever its status no longer puts it."""
    for path in (ROOT / 'preview' / record['slug'] / 'index.html', ROOT / record['category'] / record['slug'] / 'index.html'):
        if path != keep and path.exists() and GENERATED_MARK in path.read_text(encoding='utf-8'):
            path.unlink()
            if not any(path.parent.iterdir()):
                path.parent.rmdir()
            print(f'  removed  {path.relative_to(ROOT)}')


def update_block(path, body, create_before=None):
    """Replace the build-owned products block in a file. Returns True if the file changed."""
    text = path.read_text(encoding='utf-8')
    if BLOCK.search(text):
        new = BLOCK.sub(lambda m: f'{m.group(1)}\n{body}{m.group(2)}', text, count=1)
    elif create_before and body:
        new = text.replace(create_before, f'<!-- products:start -->\n{body}<!-- products:end -->\n{create_before}', 1)
    elif body:
        raise BuildError(f'{path.relative_to(ROOT)} has no <!-- products:start --> … <!-- products:end --> block to hold its published products')
    else:
        return False
    if new != text:
        path.write_text(new, encoding='utf-8')
        print(f'  updated  {path.relative_to(ROOT)}')
    return new != text


def update_listings(records):
    published = [r for _, r in records if r['status'] == 'published']
    urls = ''.join(f'  <url>\n    <loc>{SITE}{r["seo"]["canonical"]}</loc>\n    <changefreq>monthly</changefreq>\n    <priority>0.8</priority>\n  </url>\n'
                   for r in published)
    update_block(ROOT / 'sitemap.xml', urls, create_before='</urlset>')
    for category in CATEGORIES:
        page = ROOT / category / 'index.html'
        products = [r for r in published if r['category'] == category]
        if products and not page.exists():
            raise BuildError(f'{category}/index.html does not exist but has published products')
        if page.exists():
            update_block(page, category_block(products) if products else '')


def category_block(products):
    """Product cards for a category page, in that page's own variants-section / variant-card components."""
    cards = ''.join(
        f'      <a class="variant-card" href="{html.escape(r["seo"]["canonical"])}">\n'
        f'        <div class="variant-card-num">{i:02}</div>\n'
        f'        <h4>{html.escape(r["title"])}</h4>\n'
        f'        <p>{html.escape(r["short_description"])}</p>\n'
        f'      </a>\n' for i, r in enumerate(products, 1))
    return ('<div class="variants-section">\n  <div class="variants-inner">\n    <div class="variants-head">\n'
            '      <div>\n        <h2>Configure and price online</h2>\n      </div>\n'
            '      <p>Choose your options, see indicative trade prices and request a quote — all on one page.</p>\n'
            f'    </div>\n    <div class="variant-grid">\n{cards}    </div>\n  </div>\n</div>\n')


def main(check_only=False):
    records = load_records()
    if not records:
        raise BuildError('no records in data/products/')
    validate(records)
    env = Environment(loader=FileSystemLoader(ROOT / 'templates'), autoescape=True, undefined=StrictUndefined,
                      keep_trailing_newline=True)
    env.filters['br'] = lambda text: Markup('<br>'.join(html.escape(line) for line in text.split('\n')))
    pages = []
    for path, record in records:
        target = target_for(record)
        if target is None:
            print(f'  draft    {record["slug"]} — not rendered')
            pages.append((record, None, None))
            continue
        page = render(env, record)
        check_leaks(page, path.name)
        pages.append((record, target, page))
    if check_only:
        print(f'OK — {len(records)} record(s) valid, {sum(1 for _, t, _ in pages if t)} page(s) render cleanly. Nothing written.')
        return
    for record, target, page in pages:
        remove_stale(record, target)
        if target:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(page, encoding='utf-8')
            print(f'  built    {target.relative_to(ROOT)} — {len(record["variants"])} variants, status {record["status"]}')
    update_listings(records)


if __name__ == '__main__':
    try:
        main(check_only='--check' in sys.argv[1:])
    except BuildError as err:
        sys.exit(f'BUILD FAILED\n{err}')
